version: "3.8"
services:
  api:
      # image: morjuax/nestjs-dockerized
      build:
        dockerfile: Dockerfile
        context: .
      depends_on:
        - postgres
      environment:
        DATABASE_URL: postgres://services:password@postgres:5432/db
        NODE_ENV: development
        PORT: 3000
      ports:
        - "8080:3000"
  postgres:
      image: postgres:13.2
      ports:
        - "35000:5432"
      environment:
        POSTGRES_USER: services
        POSTGRES_PASSWORD: password
        POSTGRES_DB: db


